### PR TITLE
Support local Kinesis e.g. Kinesalite and add some functional tests

### PR DESCRIPTION
**Pull request by aviflax**
The functional tests run against a local Kinesis e.g. Kinesalite.

I need this for testing my own app which uses go-kinesis. But I think it’s also useful for testing go-kinesis itself. I have a feature I’d like to add but I don’t think it’d be safe to do so without some functional tests.

### CODE REVIEW

**Comment by le0pard** [comment]
Hello. Big thanks. 

But I think you need run Kinesalite inside travis, because test right now failed. https://travis-ci.org/sendgridlabs/go-kinesis/builds/55970862

**Comment by aviflax** [comment]
> Hello. Big thanks.

My pleasure!
 
> But I think you need run Kinesalite inside travis, because test right now failed. https://travis-ci.org/sendgridlabs/go-kinesis/builds/55970862

Right, of course! Will do.

**Comment by aviflax** [comment]
Looks like the build passed!

**Comment by le0pard** [comment]
thanks!

**Pull request merged**
