### PR TITLE
Extract WaitForStream function

### PR DESCRIPTION
**Pull request by harlow**
The wait code from the example app is quite helpful -- This PR give users of
the library an opportunity to leverage it without duplicating into their own libraries.
- Extract WaitForStream function

Minor changes
- Add short-circuit on CreateStream if it already exists
- Move the Get records to bottom so it fetches all the records
- Update the batch put so the records are distinguishable from single puts

### CODE REVIEW

**Comment by le0pard** [comment]
Don't forget rebase from master :)

**Comment by dlsniper** [comment]
Hi. Any plans on getting this merged? Thank you.

**Comment by le0pard** [comment]
Hello, @dlsniper . I wrote in comment, what better to change for this pull request. I think @harlow can be busy to make needed changes.

**Comment by harlow** [comment]
Ahh thanks for the bump. Yes let me rebase master and address the comments.

**Comment by harlow** [comment]
@le0pard could you please elaborate on these?

> Let's make StreamExists call optional by additional parameter (for example boolean) in method CreateStream.

To my knowledge golang doesn't allow optional parameters. Could you give me an example of what this might look like?

> Need configure inside WaitForStream how long we want to wait and max retries: again configurable by params timeout and 4 second timeout (should be default if not set)

Is your thought that the config would be part of the `kinesis` struct? 

```golang
func (kinesis *Kinesis) WaitForStream(StreamName string) {
  # ...
			time.Sleep(kinesis.WaitForStreamSeconds * time.Second)
  # ...
}
```

**Comment by le0pard** [comment]
> To my knowledge golang doesn't allow optional parameters. Could you give me an example of what this might look like?

I think most simplest way - have this separate function, which will wait (you already have this), not need to add this in `CreateStream` function. 

> Is your thought that the config would be part of the kinesis struct?

Yes, good idea. Let it be in structure.

**Pull request closed without merging**
